### ISSUE TITLE
ImportError: No module named 'utils'

### ISSUE THREAD

**Issue by lyntux** [ngageoint/gamification-server#7]
I'm trying to get things running but I'm getting the following when running "paver createdb"

---> pavement.createdb
## Captured Task Output:

---> pavement.createdb
Traceback (most recent call last):
  File "/home/lyntux/pyenv/gamification/lib/python3.4/site-packages/paver/tasks.py", line 195, in _run_task
    return do_task()
  File "/home/lyntux/pyenv/gamification/lib/python3.4/site-packages/paver/tasks.py", line 192, in do_task
    return func(**kw)
  File "pavement.py", line 87, in createdb
    from gamification import settings
  File "/home/lyntux/gamification-server/gamification/__init__.py", line 3, in <module>
    from gamification.core.models import Points
  File "/home/lyntux/gamification-server/gamification/core/models.py", line 32, in <module>
    from gamification.badges.models import ProjectBadge, ProjectBadgeToUser
  File "/home/lyntux/gamification-server/gamification/badges/**init**.py", line 1, in <module>
    from utils import registered_badges, MetaBadge
ImportError: No module named 'utils'

Any ideas?

**Comment by stephenrjones** [comment]
I've committed some changes to help resolve installation issues. Let me know if this helps at all.

**Comment by lingani** [comment]
Hello stephen, I cloned both develop and master but no chance to get rid of this issue. please help!
