### ISSUE TITLE
Requested setting CACHES, but settings are not configured

### ISSUE THREAD

**Issue by moskrc** [ngageoint/gamification-server#9]
``` python

$ paver createdb
---> pavement.createdb


Captured Task Output:
---------------------

---> pavement.createdb
Traceback (most recent call last):
  File "/Users/vit/projects/01.15/gamification-server/env/lib/python2.7/site-packages/paver/tasks.py", line 195, in _run_task
    return do_task()
  File "/Users/vit/projects/01.15/gamification-server/env/lib/python2.7/site-packages/paver/tasks.py", line 192, in do_task
    return func(**kw)
  File "pavement.py", line 87, in createdb
    from gamification import settings
  File "/Users/vit/projects/01.15/gamification-server/gamification/__init__.py", line 3, in <module>
    from gamification.core.models import Points
  File "/Users/vit/projects/01.15/gamification-server/gamification/core/models.py", line 27, in <module>
    from django.contrib.auth.models import User
  File "/Users/vit/projects/01.15/gamification-server/env/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 5, in <module>
    from django.middleware.csrf import rotate_token
  File "/Users/vit/projects/01.15/gamification-server/env/lib/python2.7/site-packages/django/middleware/csrf.py", line 16, in <module>
    from django.utils.cache import patch_vary_headers
  File "/Users/vit/projects/01.15/gamification-server/env/lib/python2.7/site-packages/django/utils/cache.py", line 26, in <module>
    from django.core.cache import get_cache
  File "/Users/vit/projects/01.15/gamification-server/env/lib/python2.7/site-packages/django/core/cache/__init__.py", line 70, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/Users/vit/projects/01.15/gamification-server/env/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Users/vit/projects/01.15/gamification-server/env/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
ImproperlyConfigured: Requested setting CACHES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

```

**Comment by sreejithc321** [comment]
try export DJANGO_SETTINGS_MODULE=gamification.settings

**Comment by georgik** [comment]
The answer is correct.

**Comment by basiljose1** [comment]
am getting ImportError: No module named myapp.settings
Thanks in advance

**Comment by WallerWalker** [comment]
This is for all beginners out there (like myself): 
for Windows use the command
"set DJANGO_SETTINGS_MODULE=<your_project_name>.settings"
